/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.fernandoce.negociosdf.formularios.menu;

/**
 *
 * @author lfern
 */
public class menuAdmin extends javax.swing.JPanel {

    /**
     * Creates new form admin
     */
    public menuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInicio = new javax.swing.JPanel();
        iconInicio = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JPanel();
        iconUsuarios = new javax.swing.JLabel();
        lblUsuarios = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JPanel();
        iconCerrarSesion = new javax.swing.JLabel();
        lblCerrarSesion = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInicio.setOpaque(false);
        btnInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btnInicio.add(iconInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 50));

        lblInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblInicio.setText("INICIO");
        btnInicio.add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 180, 50));

        add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 50));

        btnUsuarios.setOpaque(false);
        btnUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btnUsuarios.add(iconUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 50));

        lblUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarios.setText("USUARIOS");
        btnUsuarios.add(lblUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 180, 50));

        add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 250, 50));

        btnCerrarSesion.setOpaque(false);
        btnCerrarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btnCerrarSesion.add(iconCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 50, 50));

        lblCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrarSesion.setText("CERRAR SESION");
        btnCerrarSesion.add(lblCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 180, 50));

        add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 250, 50));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnCerrarSesion;
    public javax.swing.JPanel btnInicio;
    public javax.swing.JPanel btnUsuarios;
    public javax.swing.JLabel iconCerrarSesion;
    public javax.swing.JLabel iconInicio;
    public javax.swing.JLabel iconUsuarios;
    public javax.swing.JLabel lblCerrarSesion;
    public javax.swing.JLabel lblInicio;
    public javax.swing.JLabel lblUsuarios;
    // End of variables declaration//GEN-END:variables
}
