/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fernandoce.negociosdf.formularios;

import java.awt.Color;

/**
 *
 * @author lfern
 */
public class formPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form formPrincipal
     */
    public formPrincipal() {
        initComponents();
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo1 = new com.fernandoce.negociosdf.componentesExtras.fondo();
        header1 = new com.fernandoce.negociosdf.componentesExtras.header();
        jLabel1 = new javax.swing.JLabel();
        btnMin = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        fondoLeft1 = new com.fernandoce.negociosdf.componentesExtras.fondoLeft();
        panelLogo = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblNeg = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        panelDatosUser = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtuser = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCargo = new javax.swing.JLabel();
        panelContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        fondo1.setBackground(new java.awt.Color(255, 255, 255));
        fondo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("NEGOCIOS D&F - Sistema de Venta");
        header1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 600, 40));

        btnMin.setFont(new java.awt.Font("Cascadia Mono", 0, 24)); // NOI18N
        btnMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMin.setText("-");
        header1.add(btnMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 60, 40));

        btnClose.setBackground(new java.awt.Color(204, 204, 204));
        btnClose.setFont(new java.awt.Font("Cascadia Mono", 0, 24)); // NOI18N
        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setText("X");
        header1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 0, 60, 40));

        fondo1.add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 40));

        fondoLeft1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLogo.setOpaque(false);

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblNeg.setFont(new java.awt.Font("Artifakt Element Black", 1, 18)); // NOI18N
        lblNeg.setForeground(new java.awt.Color(255, 255, 255));
        lblNeg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNeg.setText("NEGOCIOS D&F");

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNeg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblNeg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        fondoLeft1.add(panelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 250, 230));

        panelMenu.setOpaque(false);

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        fondoLeft1.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 250, 610));

        fondo1.add(fondoLeft1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 800));

        panelDatosUser.setBackground(new java.awt.Color(204, 255, 255));
        panelDatosUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatosUser.setOpaque(false);
        panelDatosUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Usuario:");
        panelDatosUser.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 80, 40));

        txtuser.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        txtuser.setForeground(new java.awt.Color(0, 0, 0));
        panelDatosUser.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 300, 40));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Cargo:");
        panelDatosUser.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 70, 40));

        txtCargo.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        txtCargo.setForeground(new java.awt.Color(0, 0, 0));
        panelDatosUser.add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 10, 150, 40));

        fondo1.add(panelDatosUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 50, 1120, 60));

        panelContenido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelContenido.setOpaque(false);

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1118, Short.MAX_VALUE)
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        fondo1.add(panelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 120, 1120, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnClose;
    public javax.swing.JLabel btnMin;
    private com.fernandoce.negociosdf.componentesExtras.fondo fondo1;
    private com.fernandoce.negociosdf.componentesExtras.fondoLeft fondoLeft1;
    private com.fernandoce.negociosdf.componentesExtras.header header1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel lblIcon;
    public javax.swing.JLabel lblNeg;
    public javax.swing.JPanel panelContenido;
    public javax.swing.JPanel panelDatosUser;
    public javax.swing.JPanel panelLogo;
    public javax.swing.JPanel panelMenu;
    public javax.swing.JLabel txtCargo;
    public javax.swing.JLabel txtuser;
    // End of variables declaration//GEN-END:variables
}
