/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package com.fernandoce.negociosdf.formularios;

/**
 *
 * @author lfern
 */
public class formConfiguracion extends javax.swing.JPanel {

    /** Creates new form formUsuarios */
    public formConfiguracion() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tpConfiguracion = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CONFIGURACIÓN");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 200, 25));
        add(tpConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 1090, 605));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTabbedPane tpConfiguracion;
    // End of variables declaration//GEN-END:variables

}
